In [11]:
#sélection au hasard des 20 phrases pour la traduction
import csv
import random

COUNT = 20

with open(f'sents.csv', newline="", encoding="utf8") as f:
  reader=list(csv.reader(f))
  header,rows=reader[0],reader[1:]

sample=random.sample(rows,COUNT)

with open(f'sents_sample_{COUNT}.csv','w',newline="", encoding="utf-8") as f:
  writer=csv.writer(f)
  writer.writerow(header)
  writer.writerows(sample)

###Traduction avec le modèle Helsinki-NLP/opus-mt-en-fr

In [12]:
#Uitlisation du modèle Helsinki-NLP/opus-mt-en-fr
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

tokenizer_helsinki = AutoTokenizer.from_pretrained("Helsinki-NLP/opus-mt-en-fr")
model_helsinki = AutoModelForSeq2SeqLM.from_pretrained("Helsinki-NLP/opus-mt-en-fr")

/usr/local/lib/python3.12/dist-packages/transformers/models/marian/tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

In [13]:
import re
import pandas as pd

In [14]:
refs=[]
traduction=[]
with open("sents_sample_20.csv", newline="", encoding="utf8") as f:
  lines=list(csv.reader(f))
  row=lines[1:]
  for i in row:
    inputs=tokenizer_helsinki(i[0],return_tensors="pt")
    translation_ids=model_helsinki.generate(**inputs)
    translation=tokenizer_helsinki.decode(translation_ids[0],skip_special_tokens=True)
    #suppression des espaces insécables car présents dans les références
    clean=re.sub("\xa0"," ",i[1])
    clean=re.sub("\u2009","",clean)
    refs.append(clean)
    traduction.append(translation)

In [15]:
refs

['Décorez votre chez-vous pour les fêtes avec ces lumières festives.',
 "Dans le cimetière, on trouve d'intéressantes sculptures en marbre représentant des colombes sur certaines tombes.",
 'On trouve des spécialisations bipèdes dans les fossiles d’Australopithecus d’il y a 4,2 à 3,9 millions d’années, bien que le Sahelanthropus ait pu marcher sur deux jambes il y a déjà sept millions d’années.',
 "Bien que trois personnes aient été présentes dans la maison quand la voiture l'a percutée, aucune n'a été blessée.",
 'Un cours couvrira normalement toutes les questions abordées ici de manière beaucoup plus détaillée, généralement avec une expérience pratique.',
 "Un dîner simple et populaire, surtout en été, est le Pa amb Oli : du pain avec de l'huile d'olive, de la tomate et tous les condiments disponibles, tels que le fromage, le thon, etc.",
 'À mesure que la population VIH-positive vieillit, il faut tenir compte de problèmes comme l’hypertension et le diabète au moment d’amorcer des antirétroviraux.',
 "D'autres tribus indigènes qui peuplaient le Chaco, telles que les Guaycurú ou encore les Payaguá, survivaient essentiellement grâce à la pêche, la chasse, ou encore la cueillette.",
 "La Turquie prendrait également en charge la garde des combattants d'ISIS capturés que, selon la déclaration, les nations européennes ont refusé de rapatrier.",
 "Tard dimanche, le président des États-Unis Donald Trump, dans une déclaration faite par l'intermédiaire du secrétaire de presse, a annoncé que les troupes américaines allaient se retirer de la Syrie.",
 "Malgré les larmes versées lors de ses adieux, Oprah Winfrey a clairement dit à ses fans qu'elle serait de retour.",
 'Trente-deux greffes de demi-épaisseur ont été étudiées et elles ont été classées en deux groupes selon la nature du lit d’excision : groupe I, composé de patients ayant subi une excision tangentielle et une greffe de demi-épaisseur (n = 17) et groupe II, comportant des patients ayant subi des greffes de demi-épaisseur de fascias (n = 15).',
 'RésuméParamètres pour quantifier l’utilisation des antimicrobiens dans les parcs d’engraissement des bovins.',
 'Son pouvoir omniprésent touchait tout le monde, du roi au roturier.',
 'Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéo en déplaçant l’appareil dans l’air.',
 "Même si l'administration d'un cocktail d'anticorps, ZMapp, avait d'abord montré des signes prometteurs sur le terrain, des études formelles ont démontré que sa capacité à limiter les décès ne répondait pas aux attentes.",
 'La prononciation est relativement facile en italien, car la plupart des mots sont prononcés exactement comme ils sont écrits',
 "Seules les mutations des cellules germinales peuvent être transmises aux enfants, tandis que d'autres mutations peuvent entraîner la mort des cellules ou le cancer.",
 'Afin de communiquer efficacement les données concernant l’utilisation des antimicrobiens, l’évaluation du public cible est critique pour la présentation de l’information.',
 'Votre opérateur téléphonique local devrait pouvoir vous en dire plus au sujet de la connexion à ce service.']

In [16]:
traduction

['Décorez votre maison pour les vacances avec ces lumières festives.',
 "Dans la cour de l'église, il y a d'intéressantes sculptures en marbre de colombes au-dessus de quelques tombes.",
 "On trouve des spécialisations bipédiques dans les fossiles d'Australopithecus de 4,2 à 3,9 millions d'années auparavant, bien que l'anthrope sahélien ait peut-être marché sur deux pattes il y a sept millions d'années.",
 "Bien que trois personnes se trouvaient à l'intérieur de la maison lorsque la voiture l'a touchée, aucune d'entre elles n'a été blessée.",
 'Un cours portera normalement sur toutes les questions abordées ici de manière beaucoup plus détaillée, généralement avec une expérience pratique.',
 "Un simple dîner populaire, surtout pendant l'été, est le Pa amb Oli: Pain à l'huile d'olive, tomate, et tous les condiments disponibles tels que le fromage, thon, etc.",
 "À mesure que la population séropositive vieillit, des questions telles que l'hypertension et le diabète doivent être prises en compte lors de l'initiation du TAR.",
 "La région du Chaco abrite d ' autres groupes de tribus autochtones comme les Guaycurú et Payaguá, qui ont survécu à la chasse, à la cueillette et à la pêche.",
 "La Turquie prendrait également le contrôle des combattants de l'Etat islamique capturés qui, selon la déclaration, ont refusé de rapatrier les nations européennes.",
 "À la fin de dimanche, le président américain Donald Trump, dans une déclaration prononcée par l'intermédiaire du secrétaire à la presse, a annoncé que les troupes américaines quitteraient la Syrie.",
 "Bien que Winfrey ait pleuré dans ses adieux, elle a dit clairement à ses fans qu'elle sera de retour.",
 "Trente-deux greffes de peau fendue ont été étudiées et placées en deux groupes selon la nature du lit d'excision : le groupe I était composé de patients ayant subi une excision tangentielle et une greffe de peau fendue (n=17), et le groupe II était composé de patients ayant des greffes de peau fendue placées sur des lits fasciaux (n=15).",
 "Mesures pour quantifier l'utilisation d'antimicrobiens dans les parcs d'engraissement du boeuf.",
 'Son pouvoir tout-pervade a affecté tout le monde du roi au communier.',
 "Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéo en déplaçant l'appareil dans les airs.",
 "Un cocktail d'anticorps, ZMapp, s'est montré initialement prometteur sur le terrain, mais des études formelles ont indiqué qu'il avait moins d'avantages que recherché pour prévenir la mort.",
 'La prononciation est relativement facile en italien puisque la plupart des mots sont prononcés exactement comment ils sont écrits',
 'Seules les mutations dans les cellules germinales peuvent être transmises aux enfants, tandis que les mutations ailleurs peuvent causer la mort cellulaire ou le cancer.',
 "Pour communiquer efficacement les données sur l'utilisation des médicaments antimicrobiens, l'évaluation du public cible est essentielle à la présentation de l'information.",
 "Votre fournisseur local de services téléphoniques devrait être en mesure de fournir plus d'informations sur la connexion à ce service."]

Mise du fichier de phrases sample sous format dataframe afin d'ajouter les différentes traductions

In [19]:
phrases_df=pd.read_csv("sents_sample_20.csv")

In [31]:
phrases_df["traduction_helsinki"]=traduction

In [32]:
phrases_df

,en,fr,traduction_helsinki
0,Decorate your home for the holidays with these...,Décorez votre chez-vous pour les fêtes avec ce...,Décorez votre maison pour les vacances avec ce...
1,"In the churchyard, there are interesting marbl...","Dans le cimetière, on trouve d'intéressantes s...","Dans la cour de l'église, il y a d'intéressant..."
2,Bipedal specializations are found in Australop...,On trouve des spécialisations bipèdes dans les...,On trouve des spécialisations bipédiques dans ...
3,Although three people were inside the house wh...,Bien que trois personnes aient été présentes d...,Bien que trois personnes se trouvaient à l'int...
4,A course will normally cover all the issues di...,Un cours couvrira normalement toutes les quest...,Un cours portera normalement sur toutes les qu...
5,"A simple popular dinner, especially during the...","Un dîner simple et populaire, surtout en été, ...","Un simple dîner populaire, surtout pendant l'é..."
6,"As the HIV-positive population ages, issues su...",À mesure que la population VIH-positive vieill...,À mesure que la population séropositive vieill...
7,The Chaco region was home to other groups of i...,D'autres tribus indigènes qui peuplaient le Ch...,La région du Chaco abrite d ' autres groupes d...
8,Turkey would also take over guarding captured ...,La Turquie prendrait également en charge la ga...,La Turquie prendrait également le contrôle des...
9,"Late on Sunday, the United States President Do...","Tard dimanche, le président des États-Unis Don...","À la fin de dimanche, le président américain D..."
10,"Although Winfrey was tearful in her farewell, ...","Malgré les larmes versées lors de ses adieux, ...","Bien que Winfrey ait pleuré dans ses adieux, e..."
11,Thirty-two split-skin grafts were studied and ...,Trente-deux greffes de demi-épaisseur ont été ...,Trente-deux greffes de peau fendue ont été étu...
12,Metrics for quantifying antimicrobial use in b...,RésuméParamètres pour quantifier l’utilisation...,Mesures pour quantifier l'utilisation d'antimi...
13,Its all-pervading power affected everyone from...,Son pouvoir omniprésent touchait tout le monde...,Son pouvoir tout-pervade a affecté tout le mon...
14,This will allow players to control actions and...,Cela permettra aux joueurs de contrôler les ac...,Cela permettra aux joueurs de contrôler les ac...
15,"One antibody cocktail, ZMapp, initially showed...",Même si l'administration d'un cocktail d'antic...,"Un cocktail d'anticorps, ZMapp, s'est montré i..."
16,Pronunciation is relatively easy in Italian si...,La prononciation est relativement facile en it...,La prononciation est relativement facile en it...
17,Only mutations in germ-line cells can be passe...,Seules les mutations des cellules germinales p...,Seules les mutations dans les cellules germina...
18,To effectively communicate antimicrobial drug ...,Afin de communiquer efficacement les données c...,Pour communiquer efficacement les données sur ...
19,Your local telephone service provider should b...,Votre opérateur téléphonique local devrait pou...,Votre fournisseur local de services téléphoniq...

###Évaluation des traductions de Helsinki-NLP/opus-mt-en-fr

Évaluation avec BLEU

In [34]:
!pip install sacrebleu jiwer pymeteor nltk datasets transformers evaluate bert_score

Collecting sacrebleu
  Downloading sacrebleu-2.5.1-py3-none-any.whl.metadata (51 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 3.8 MB/s eta 0:00:00
Collecting jiwer
  Downloading jiwer-4.0.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pymeteor
  Downloading pyMeteor-0.0.5.tar.gz (12 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Collecting evaluate
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting bert_score
  Downloading bert_score-0.3.13-py3-none-any.whl.metadata (15 kB)
Collecting portalocker (from sacrebleu)
  Downloading portalocker-3.2.0-py3-none-any.whl.metadata (8.7 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2025.11.3)
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (0.9.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (2.0.2)
Collecting colorama (from sacrebleu)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from sacrebleu) (6.0.2)
Requirement already satisfied: click>=8.1.8 in /usr/local/lib/python3.12/dist-packages (from jiwer) (8.3.1)
Collecting rapidfuzz>=3.9.7 (from jiwer)
  Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.20.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.9.0+cu126)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert_score) (3.10.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2025.11.12)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.5.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (3.2.5)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert_score) (3.0.3)
Downloading sacrebleu-2.5.1-py3-none-any.whl (104 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 6.3 MB/s eta 0:00:00
Downloading jiwer-4.0.0-py3-none-any.whl (23 kB)
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 6.0 MB/s eta 0:00:00
Downloading bert_score-0.3.13-py3-none-any.whl (61 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 5.7 MB/s eta 0:00:00
Downloading rapidfuzz-3.14.3-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 47.8 MB/s eta 0:00:00
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Downloading portalocker-3.2.0-py3-none-any.whl (22 kB)
Building wheels for collected packages: pymeteor
  Building wheel for pymeteor (setup.py) ... done
  Created wheel for pymeteor: filename=pyMeteor-0.0.5-py3-none-any.whl size=14685 sha256=219c9fd65cd85e4a1e8413add857249f2a803dc427202df21f4d222a68d3e145
  Stored in directory: /root/.cache/pip/wheels/62/33/cb/b9e307471072cf7bcc89aa1ce6f97f8c4a7dd320e5ba24db44
Successfully built pymeteor
Installing collected packages: pymeteor, rapidfuzz, portalocker, colorama, sacrebleu, jiwer, evaluate, bert_score
Successfully installed bert_score-0.3.13 colorama-0.4.6 evaluate-0.4.6 jiwer-4.0.0 portalocker-3.2.0 pymeteor-0.0.5 rapidfuzz-3.14.3 sacrebleu-2.5.1

In [35]:
import sacrebleu
from sacrebleu.metrics import BLEU

Afin de calculer la moyenne des différents scores, j'ai normalisé les scores retournés par chaque métrique, étant donné qu'une simple moyenne des score serait biaisée car pour WER par exemple, plus le score est éloigné de 1, meilleure est la traduction, or c'est le contraire avec BLEU (plus le score est proche de 1, meilleure est la traduction). La normalisation a été inspirée par chatGPT

In [78]:
bleu=BLEU(max_ngram_order=4)
res=bleu.corpus_score(traduction,[refs])
score_bleu_helsinki=res.score
print(f'score bleu helsinki: {score_bleu_helsinki}')
score_bleu_helsinki_norm=score_bleu_helsinki/100
print(f'score bleu normalisé: {score_bleu_helsinki_norm}')

score bleu helsinki: 39.914905549563386
score bleu normalisé: 0.39914905549563384

Évaluation avec WER

In [79]:
#Calcul avec WER
from jiwer import wer
wer_helsinki=wer(traduction,refs)
wer_helsinki_norm=1-wer_helsinki
print(f'Score wer_helsinki: {wer_helsinki}')
print(f'score wer helsinki normalisé: {wer_helsinki_norm}')

Score wer_helsinki: 0.4957627118644068
score wer helsinki normalisé: 0.5042372881355932

Évaluation avec BERTScore

In [71]:
#Calcul avec BertScore
from evaluate import load
bertscore=load("bertscore")
results=bertscore.compute(predictions=traduction,references=refs,lang="fr")["precision"]

In [72]:
results

[0.9472126960754395,
 0.8903598189353943,
 0.884494423866272,
 0.8978612422943115,
 0.9660439491271973,
 0.948560893535614,
 0.8338726162910461,
 0.865327000617981,
 0.8975440859794617,
 0.9301248788833618,
 0.8857467174530029,
 0.8972938060760498,
 0.9049400091171265,
 0.8111748099327087,
 0.9754812121391296,
 0.8450847864151001,
 0.9707332849502563,
 0.9447810649871826,
 0.9144678115844727,
 0.8407975435256958]

In [80]:
mean_precision_helsinki=mean(results)
print(f'Moyenne de la précision: {mean_precision_helsinki}')

Moyenne de la précision: 0.9025951325893402

In [81]:
#calcul du score global normalisé des 3 mesures pour Helsinki
score_moyen_helsinki=score_bleu_helsinki_norm+wer_helsinki_norm+mean_precision_helsinki/3
score_moyen_helsinki

1.2042513878276737

###Traduction avec le modèle openai/gpt-oss-120b:free

In [82]:
import requests, json

In [83]:
trans_dict={}
with open("sents_sample_20.csv", newline="", encoding="utf8") as f:
  lines_autoreg=list(csv.reader(f))
  row_autoreg=lines_autoreg[1:]
  for i in row_autoreg:
    response = requests.post(
    url="https://openrouter.ai/api/v1/chat/completions",
    headers={
            "Authorization": "Bearer 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",
            "Content-Type": "application/json",
          },
    data=json.dumps({ "model": "openai/gpt-oss-120b:free",
                            "messages": [ { "role": "user",
                                          "content": f'''Translate the following text from english to french. For each translation,
                                          respond in the form of a valid json object following this format:
                                          There should be no text before or after, simply follow this format.
                                          {{"english": "...",
                                           "french": "..."}}
                                           The sentences are from diverse domains: astronomy, chemistry, daily life and others:: {i[0]}''' }
                                        ], }))

    response=response.json()
    if "choices" in response:
      content=response['choices'][0]['message']["content"]
      try:
        data=json.loads(content)
        trans_dict[data["english"]]=data["french"]
      except json.JSONDecodeError:
        print("json invalide",content)
      print(response['choices'][0]['message']["content"])
    else:
        print(f'Erreur: {response}')

{"english":"Decorate your home for the holidays with these festive lights.","french":"Décorez votre maison pour les fêtes avec ces lumières festives."}
{"english":"In the churchyard, there are interesting marble sculptures of doves over some tombs.","french":"Dans le cimetière, il y a d'intéressantes sculptures en marbre de colombes au-dessus de certaines tombes."}
{"english":"Bipedal specializations are found in Australopithecus fossils from 4.2-3.9 million years ago, although Sahelanthropus may have walked on two legs as early as seven million years ago.","french":"Des spécialisations bipèdes sont observées dans les fossiles d'Australopithèque datant de 4,2 à 3,9 millions d'années, bien que le Sahelanthropus ait pu marcher sur deux jambes dès il y a sept millions d'années."}
{"english":"Although three people were inside the house when the car impacted it, none of them were hurt.","french":"Bien que trois personnes se trouvaient à l'intérieur de la maison lorsque la voiture l'a percutée, aucune d'elles n'a été blessée."}
{"english":"A course will normally cover all the issues discussed here in far greater detail, usually with practical experience.","french":"Un cours couvrira normalement toutes les questions abordées ici en bien plus de détail, généralement avec une expérience pratique."}
{"english":"A simple popular dinner, especially during the summer, is the Pa amb Oli: Bread with olive oil, tomato, and any available condiments such as cheese, tunafish, etc.","french":"Un dîner simple et populaire, surtout pendant l'été, est le Pa amb Oli : pain avec de l'huile d'olive, de la tomate, et tout condiment disponible tel que du fromage, du thon, etc."}
{"english":"As the HIV-positive population ages, issues such as hypertension and diabetes must be taken into account when initiating ART.","french":"À mesure que la population séropositive au VIH vieillit, des problèmes tels que l'hypertension et le diabète doivent être pris en compte lors du démarrage de la TAR."}
{"english":"The Chaco region was home to other groups of indigenous tribes such as the Guaycurú and Payaguá, who survived by hunting, gathering and fishing.","french":"La région du Chaco était le foyer d'autres groupes de tribus indigènes tels que les Guaycurú et les Payaguá, qui survivaient en chassant, en cueillant et en pêchant."}
{"english":"Turkey would also take over guarding captured ISIS fighters which, the statement said, European nations have refused to repatriate.","french":"La Turquie prendrait également en charge la garde des combattants de l'EI capturés, que, selon la déclaration, les nations européennes ont refusé de rapatrier."}
{"english":"Late on Sunday, the United States President Donald Trump, in a statement delivered via the press secretary, announced US troops would be leaving Syria.","french":"Tard dimanche, le président des États-Unis Donald Trump, dans une déclaration transmise par le porte-parole, a annoncé que les troupes américaines quitteraient la Syrie."}
{"english":"Although Winfrey was tearful in her farewell, she made it clear to her fans she will be back.","french":"Bien que Winfrey ait été en larmes lors de ses adieux, elle a clairement indiqué à ses fans qu'elle reviendra."}
{"english":"Thirty-two split-skin grafts were studied and these were placed into two groups based on the nature of the bed of excision: group I consisted of patients who underwent tangential excision and split-skin grafting (n=17), and group II consisted of patients with split-skin grafts placed onto fascial beds (n=15).","french":"Trente-deux greffes de peau mince ont été étudiées et réparties en deux groupes selon la nature du lit d'excision : le groupe I était composé de patients ayant subi une excision tangentielle et une greffe de peau mince (n=17), et le groupe II était composé de patients avec des greffes de peau mince placées sur des lits fasciaux (n=15)."}
{"english": "Metrics for quantifying antimicrobial use in beef feedlots.", "french": "Métriques pour quantifier l'utilisation d'antimicrobiens dans les feedlots de bœuf."}
{"english":"Its all-pervading power affected everyone from king to commoner.","french":"Son pouvoir omniprésent a affecté tout le monde, du roi au roturier."}
{"english":"This will allow players to control actions and movements in video games by moving the device through the air.","french":"Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéo en déplaçant l'appareil dans l'air."}
{"english":"One antibody cocktail, ZMapp, initially showed promise in the field, but formal studies indicated it had less benefit than sought in preventing death.","french":"Un cocktail d'anticorps, ZMapp, a d'abord montré des promesses sur le terrain, mais des études formelles ont indiqué qu'il était moins bénéfique que prévu pour prévenir les décès."}
{"english":"Pronunciation is relatively easy in Italian since most words are pronounced exactly how they are written","french":"La prononciation est relativement facile en italien, car la plupart des mots se prononcent exactement comme ils sont écrits"}
{"english":"Only mutations in germ-line cells can be passed on to children, while mutations elsewhere can cause cell-death or cancer.","french":"Seules les mutations dans les cellules germinales peuvent être transmises aux enfants, tandis que les mutations ailleurs peuvent provoquer la mort cellulaire ou le cancer."}
{"english":"To effectively communicate antimicrobial drug use data, evaluation of the target audience is critical to presenting the information.","french":"Pour communiquer efficacement les données sur l'utilisation des médicaments antimicrobiens, l'évaluation du public cible est essentielle pour présenter l'information."}
{"english":"Your local telephone service provider should be able to give more information about connecting to this service.","french":"Votre fournisseur de services téléphoniques local devrait être en mesure de fournir plus d'informations sur la connexion à ce service."}

In [84]:
trans_dict.values()

dict_values(['Décorez votre maison pour les fêtes avec ces lumières festives.', "Dans le cimetière, il y a d'intéressantes sculptures en marbre de colombes au-dessus de certaines tombes.", "Des spécialisations bipèdes sont observées dans les fossiles d'Australopithèque datant de 4,2 à 3,9 millions d'années, bien que le Sahelanthropus ait pu marcher sur deux jambes dès il y a sept millions d'années.", "Bien que trois personnes se trouvaient à l'intérieur de la maison lorsque la voiture l'a percutée, aucune d'elles n'a été blessée.", 'Un cours couvrira normalement toutes les questions abordées ici en bien plus de détail, généralement avec une expérience pratique.', "Un dîner simple et populaire, surtout pendant l'été, est le Pa amb Oli : pain avec de l'huile d'olive, de la tomate, et tout condiment disponible tel que du fromage, du thon, etc.", "À mesure que la population séropositive au VIH vieillit, des problèmes tels que l'hypertension et le diabète doivent être pris en compte lors du démarrage de la TAR.", "La région du Chaco était le foyer d'autres groupes de tribus indigènes tels que les Guaycurú et les Payaguá, qui survivaient en chassant, en cueillant et en pêchant.", "La Turquie prendrait également en charge la garde des combattants de l'EI capturés, que, selon la déclaration, les nations européennes ont refusé de rapatrier.", 'Tard dimanche, le président des États-Unis Donald Trump, dans une déclaration transmise par le porte-parole, a annoncé que les troupes américaines quitteraient la Syrie.', "Bien que Winfrey ait été en larmes lors de ses adieux, elle a clairement indiqué à ses fans qu'elle reviendra.", "Trente-deux greffes de peau mince ont été étudiées et réparties en deux groupes selon la nature du lit d'excision : le groupe I était composé de patients ayant subi une excision tangentielle et une greffe de peau mince (n=17), et le groupe II était composé de patients avec des greffes de peau mince placées sur des lits fasciaux (n=15).", "Métriques pour quantifier l'utilisation d'antimicrobiens dans les feedlots de bœuf.", 'Son pouvoir omniprésent a affecté tout le monde, du roi au roturier.', "Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéo en déplaçant l'appareil dans l'air.", "Un cocktail d'anticorps, ZMapp, a d'abord montré des promesses sur le terrain, mais des études formelles ont indiqué qu'il était moins bénéfique que prévu pour prévenir les décès.", 'La prononciation est relativement facile en italien, car la plupart des mots se prononcent exactement comme ils sont écrits', 'Seules les mutations dans les cellules germinales peuvent être transmises aux enfants, tandis que les mutations ailleurs peuvent provoquer la mort cellulaire ou le cancer.', "Pour communiquer efficacement les données sur l'utilisation des médicaments antimicrobiens, l'évaluation du public cible est essentielle pour présenter l'information.", "Votre fournisseur de services téléphoniques local devrait être en mesure de fournir plus d'informations sur la connexion à ce service."])

In [85]:
traductions_api=[]
for i in trans_dict.values():
  traductions_api.append(i)
traductions_api

['Décorez votre maison pour les fêtes avec ces lumières festives.',
 "Dans le cimetière, il y a d'intéressantes sculptures en marbre de colombes au-dessus de certaines tombes.",
 "Des spécialisations bipèdes sont observées dans les fossiles d'Australopithèque datant de 4,2 à 3,9 millions d'années, bien que le Sahelanthropus ait pu marcher sur deux jambes dès il y a sept millions d'années.",
 "Bien que trois personnes se trouvaient à l'intérieur de la maison lorsque la voiture l'a percutée, aucune d'elles n'a été blessée.",
 'Un cours couvrira normalement toutes les questions abordées ici en bien plus de détail, généralement avec une expérience pratique.',
 "Un dîner simple et populaire, surtout pendant l'été, est le Pa amb Oli : pain avec de l'huile d'olive, de la tomate, et tout condiment disponible tel que du fromage, du thon, etc.",
 "À mesure que la population séropositive au VIH vieillit, des problèmes tels que l'hypertension et le diabète doivent être pris en compte lors du démarrage de la TAR.",
 "La région du Chaco était le foyer d'autres groupes de tribus indigènes tels que les Guaycurú et les Payaguá, qui survivaient en chassant, en cueillant et en pêchant.",
 "La Turquie prendrait également en charge la garde des combattants de l'EI capturés, que, selon la déclaration, les nations européennes ont refusé de rapatrier.",
 'Tard dimanche, le président des États-Unis Donald Trump, dans une déclaration transmise par le porte-parole, a annoncé que les troupes américaines quitteraient la Syrie.',
 "Bien que Winfrey ait été en larmes lors de ses adieux, elle a clairement indiqué à ses fans qu'elle reviendra.",
 "Trente-deux greffes de peau mince ont été étudiées et réparties en deux groupes selon la nature du lit d'excision : le groupe I était composé de patients ayant subi une excision tangentielle et une greffe de peau mince (n=17), et le groupe II était composé de patients avec des greffes de peau mince placées sur des lits fasciaux (n=15).",
 "Métriques pour quantifier l'utilisation d'antimicrobiens dans les feedlots de bœuf.",
 'Son pouvoir omniprésent a affecté tout le monde, du roi au roturier.',
 "Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéo en déplaçant l'appareil dans l'air.",
 "Un cocktail d'anticorps, ZMapp, a d'abord montré des promesses sur le terrain, mais des études formelles ont indiqué qu'il était moins bénéfique que prévu pour prévenir les décès.",
 'La prononciation est relativement facile en italien, car la plupart des mots se prononcent exactement comme ils sont écrits',
 'Seules les mutations dans les cellules germinales peuvent être transmises aux enfants, tandis que les mutations ailleurs peuvent provoquer la mort cellulaire ou le cancer.',
 "Pour communiquer efficacement les données sur l'utilisation des médicaments antimicrobiens, l'évaluation du public cible est essentielle pour présenter l'information.",
 "Votre fournisseur de services téléphoniques local devrait être en mesure de fournir plus d'informations sur la connexion à ce service."]

In [87]:
phrases_df["traduction_gpt"]=traductions_api

In [88]:
phrases_df

,en,fr,traduction_helsinki,traduction_gpt
0,Decorate your home for the holidays with these...,Décorez votre chez-vous pour les fêtes avec ce...,Décorez votre maison pour les vacances avec ce...,Décorez votre maison pour les fêtes avec ces l...
1,"In the churchyard, there are interesting marbl...","Dans le cimetière, on trouve d'intéressantes s...","Dans la cour de l'église, il y a d'intéressant...","Dans le cimetière, il y a d'intéressantes scul..."
2,Bipedal specializations are found in Australop...,On trouve des spécialisations bipèdes dans les...,On trouve des spécialisations bipédiques dans ...,Des spécialisations bipèdes sont observées dan...
3,Although three people were inside the house wh...,Bien que trois personnes aient été présentes d...,Bien que trois personnes se trouvaient à l'int...,Bien que trois personnes se trouvaient à l'int...
4,A course will normally cover all the issues di...,Un cours couvrira normalement toutes les quest...,Un cours portera normalement sur toutes les qu...,Un cours couvrira normalement toutes les quest...
5,"A simple popular dinner, especially during the...","Un dîner simple et populaire, surtout en été, ...","Un simple dîner populaire, surtout pendant l'é...","Un dîner simple et populaire, surtout pendant ..."
6,"As the HIV-positive population ages, issues su...",À mesure que la population VIH-positive vieill...,À mesure que la population séropositive vieill...,À mesure que la population séropositive au VIH...
7,The Chaco region was home to other groups of i...,D'autres tribus indigènes qui peuplaient le Ch...,La région du Chaco abrite d ' autres groupes d...,La région du Chaco était le foyer d'autres gro...
8,Turkey would also take over guarding captured ...,La Turquie prendrait également en charge la ga...,La Turquie prendrait également le contrôle des...,La Turquie prendrait également en charge la ga...
9,"Late on Sunday, the United States President Do...","Tard dimanche, le président des États-Unis Don...","À la fin de dimanche, le président américain D...","Tard dimanche, le président des États-Unis Don..."
10,"Although Winfrey was tearful in her farewell, ...","Malgré les larmes versées lors de ses adieux, ...","Bien que Winfrey ait pleuré dans ses adieux, e...",Bien que Winfrey ait été en larmes lors de ses...
11,Thirty-two split-skin grafts were studied and ...,Trente-deux greffes de demi-épaisseur ont été ...,Trente-deux greffes de peau fendue ont été étu...,Trente-deux greffes de peau mince ont été étud...
12,Metrics for quantifying antimicrobial use in b...,RésuméParamètres pour quantifier l’utilisation...,Mesures pour quantifier l'utilisation d'antimi...,Métriques pour quantifier l'utilisation d'anti...
13,Its all-pervading power affected everyone from...,Son pouvoir omniprésent touchait tout le monde...,Son pouvoir tout-pervade a affecté tout le mon...,Son pouvoir omniprésent a affecté tout le mond...
14,This will allow players to control actions and...,Cela permettra aux joueurs de contrôler les ac...,Cela permettra aux joueurs de contrôler les ac...,Cela permettra aux joueurs de contrôler les ac...
15,"One antibody cocktail, ZMapp, initially showed...",Même si l'administration d'un cocktail d'antic...,"Un cocktail d'anticorps, ZMapp, s'est montré i...","Un cocktail d'anticorps, ZMapp, a d'abord mont..."
16,Pronunciation is relatively easy in Italian si...,La prononciation est relativement facile en it...,La prononciation est relativement facile en it...,La prononciation est relativement facile en it...
17,Only mutations in germ-line cells can be passe...,Seules les mutations des cellules germinales p...,Seules les mutations dans les cellules germina...,Seules les mutations dans les cellules germina...
18,To effectively communicate antimicrobial drug ...,Afin de communiquer efficacement les données c...,Pour communiquer efficacement les données sur ...,Pour communiquer efficacement les données sur ...
19,Your local telephone service provider should b...,Votre opérateur téléphonique local devrait pou...,Votre fournisseur local de services téléphoniq...,Votre fournisseur de services téléphoniques lo...

###Evaluation du modèle openai/gpt-oss-120b:free

Avec BLEU

In [89]:
#BLEU
score_bleu2=bleu.corpus_score(traductions_api,[refs])
score_bleu_gpt=score_bleu2.score
score_bleu_gpt_norm=score_bleu_gpt/100
print(f"score bleu gpt: {score_bleu_gpt}")
print(f"score bleu gpt normalisé: {score_bleu_gpt_norm}")

score bleu gpt: 47.98359595078627
score bleu gpt normalisé: 0.4798359595078627

In [90]:
wer_gpt=wer(traductions_api,refs)
wer_gpt_norm=1-wer_gpt
print(f"score wer gpt: {wer_gpt}")
print(f"score wer gpt normalisé: {wer_gpt_norm}")

score wer gpt: 0.45085470085470086
score wer gpt normalisé: 0.5491452991452992

In [91]:
results_gpt=bertscore.compute(predictions=traductions_api,references=refs,lang="fr")["precision"]

In [92]:
results_gpt

[0.9657841324806213,
 0.9331809282302856,
 0.915090024471283,
 0.9155887365341187,
 0.9546915292739868,
 0.963449239730835,
 0.8432630300521851,
 0.8302127122879028,
 0.9594529867172241,
 0.9564493894577026,
 0.8726162910461426,
 0.8985693454742432,
 0.8708863854408264,
 0.9620883464813232,
 0.9801303744316101,
 0.8651247620582581,
 0.9753376245498657,
 0.9459185600280762,
 0.9107288122177124,
 0.8479678630828857]

In [94]:
mean_precision_gpt=mean(results_gpt)
print(f'precision moyenne gpt: {mean_precision_gpt} ')

precision moyenne gpt: 0.9183265537023544

In [95]:
#calcul du score global normalisé des 3 mesures pour openai/gpt-oss-120b:free
score_moyen_gpt=score_bleu_gpt_norm+wer_gpt_norm+mean_precision_gpt/3
score_moyen_gpt

1.33509010988728

###Traduction avec google/flan-t5-large

In [96]:
!pip install -U transformers accelerate

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.3)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.12.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.36.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers) (2.32.4)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.9.0+cu126)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (2025.3.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (4.15.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.5.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers) (2025.11.12)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)

In [97]:
from transformers import T5Tokenizer, T5ForConditionalGeneration

tokenizer_google=T5Tokenizer.from_pretrained("google/flan-t5-large")
model_google=T5ForConditionalGeneration.from_pretrained("google/flan-t5-large").to("cuda")

tokenizer_config.json: 0.00B [00:00, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565

config.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/3.13G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/147 [00:00<?, ?B/s]

In [98]:
reference=[]
translation=[]
with open("sents_sample_20.csv", newline="", encoding="utf8") as f:
  lines=list(csv.reader(f))
  row_google=lines[1:]
  for i in row_google:
    nettoy=re.sub("\xa0","",i[1])
    nettoy=re.sub("\u2009","",nettoy)
    reference.append(nettoy)
    input_text=f'Translate from english to french {i[0]}'
    input_ids=tokenizer_google(input_text,return_tensors="pt").input_ids.to("cuda")
    outputs=model_google.generate(input_ids,max_length=100)
    out=tokenizer_google.decode(outputs[0], skip_special_tokens=True)
    translation.append(out)
    print(out)

Décorer votre maison pour les fêtes avec ces étoiles festivités.
Dans le jardin de la église, il y a des sculptures de marbre intéressantes de pêches sur des tombes.
Les spécifications bipedales sont trouvées dans les fossiles de l'Autropia d'environ 4,2 à 3,9 millions d'âge, bien que Sahelanthropus aurait pu se déplacer sur deux femelles dès l'âge de 7 millions d'âge.
Bien que trois personnes étaient à l'intérieur de la maison quand le voiture s'affectait, aucune d'elles n'a été blessée.
Une formation s'étendra généralement à tous les questions évoquées ici en profondeur, en utilisant généralement une expérience pratique.
Une simple et populaire supper, en particulier pendant la saison, est la Pa amb Oli : Pan avec l'huile d'olive, le tomato et touts condiments disponibles tels que la chèvre, le tuna, etc.
Comme la population positive à la VIH agisse, les questions telles que la hypertension et la diabète doivent être pris en compte lorsqu'on ait en train d'initier l'ART.
La région du Chaco était l'hôte d'autres groupes de tribes autochtones comme les Guaycur et Payaguá, qui s'établiront par la chasse, la collectivité et la pêche.
L'État partie serait également chargé de la garde des combattants de l'ISIS qui, selon la déclaration, ont été retombés par les pays européens.
L'après-midi, le président américain Donald Trump a annoncé que les troupes américaines seraient à l'exclusion de la Syrie.
Même si Winfrey a été tremblée lors de son farewell, elle a fait clairement à ses fans qu'elle s'arrivera.
Thirty-two grafts de sèvres à sèvres ont été étudiés et les grafts ont été établies dans deux groupes selon la nature de la cote d'excision : groupe I consiste à des patients qui ont undergone l'excision tangentiale et l'étayage à sèvres
Métriques pour quantifier l'utilisation antimicrobiens dans les étoiles de bétail.
Il a eu une puissance omniprésente qui a affecté tous, du roi à la comménère.
Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéos en movant le dispositif à travers l'air.
Un cocktail d'antibodies, ZMapp, a eu une promesse dans ce domaine, mais les études officielles indiquent qu'il avait moins de bénéfice que l'on avait souhaité en prévenir la mort.
La pronunciation est relativement facile en Italienne, car la plupart des mots sont pronunciés exactement comme ils sont écrits
Les mutations dans les cellules germineuses peuvent être transmissées à l'enfant, alors que les mutations ailleurs peuvent causer la mort des cellules ou le cancer.
Pour communiquer efficacement les données sur l'utilisation des médicaments antimicrobiens, l'évaluation du lecteur cible est essentielle pour la présentation des renseignements.
Votre fournisseur de services de téléphone local devrait pouvoir donner plus d'information sur la connexion à ce service.

In [99]:
reference

['Décorez votre chez-vous pour les fêtes avec ces lumières festives.',
 "Dans le cimetière, on trouve d'intéressantes sculptures en marbre représentant des colombes sur certaines tombes.",
 'On trouve des spécialisations bipèdes dans les fossiles d’Australopithecus d’il y a 4,2 à 3,9millions d’années, bien que le Sahelanthropus ait pu marcher sur deux jambes il y a déjà sept millions d’années.',
 "Bien que trois personnes aient été présentes dans la maison quand la voiture l'a percutée, aucune n'a été blessée.",
 'Un cours couvrira normalement toutes les questions abordées ici de manière beaucoup plus détaillée, généralement avec une expérience pratique.',
 "Un dîner simple et populaire, surtout en été, est le Pa amb Oli: du pain avec de l'huile d'olive, de la tomate et tous les condiments disponibles, tels que le fromage, le thon, etc.",
 'À mesure que la population VIH-positive vieillit, il faut tenir compte de problèmes comme l’hypertension et le diabète au moment d’amorcer des antirétroviraux.',
 "D'autres tribus indigènes qui peuplaient le Chaco, telles que les Guaycurú ou encore les Payaguá, survivaient essentiellement grâce à la pêche, la chasse, ou encore la cueillette.",
 "La Turquie prendrait également en charge la garde des combattants d'ISIS capturés que, selon la déclaration, les nations européennes ont refusé de rapatrier.",
 "Tard dimanche, le président des États-Unis Donald Trump, dans une déclaration faite par l'intermédiaire du secrétaire de presse, a annoncé que les troupes américaines allaient se retirer de la Syrie.",
 "Malgré les larmes versées lors de ses adieux, Oprah Winfrey a clairement dit à ses fans qu'elle serait de retour.",
 'Trente-deux greffes de demi-épaisseur ont été étudiées et elles ont été classées en deux groupes selon la nature du lit d’excision : groupe I, composé de patients ayant subi une excision tangentielle et une greffe de demi-épaisseur (n = 17) et groupe II, comportant des patients ayant subi des greffes de demi-épaisseur de fascias (n = 15).',
 'RésuméParamètres pour quantifier l’utilisation des antimicrobiens dans les parcs d’engraissement des bovins.',
 'Son pouvoir omniprésent touchait tout le monde, du roi au roturier.',
 'Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéo en déplaçant l’appareil dans l’air.',
 "Même si l'administration d'un cocktail d'anticorps, ZMapp, avait d'abord montré des signes prometteurs sur le terrain, des études formelles ont démontré que sa capacité à limiter les décès ne répondait pas aux attentes.",
 'La prononciation est relativement facile en italien, car la plupart des mots sont prononcés exactement comme ils sont écrits',
 "Seules les mutations des cellules germinales peuvent être transmises aux enfants, tandis que d'autres mutations peuvent entraîner la mort des cellules ou le cancer.",
 'Afin de communiquer efficacement les données concernant l’utilisation des antimicrobiens, l’évaluation du public cible est critique pour la présentation de l’information.',
 'Votre opérateur téléphonique local devrait pouvoir vous en dire plus au sujet de la connexion à ce service.']

In [100]:
translation

['Décorer votre maison pour les fêtes avec ces étoiles festivités.',
 'Dans le jardin de la église, il y a des sculptures de marbre intéressantes de pêches sur des tombes.',
 "Les spécifications bipedales sont trouvées dans les fossiles de l'Autropia d'environ 4,2 à 3,9 millions d'âge, bien que Sahelanthropus aurait pu se déplacer sur deux femelles dès l'âge de 7 millions d'âge.",
 "Bien que trois personnes étaient à l'intérieur de la maison quand le voiture s'affectait, aucune d'elles n'a été blessée.",
 "Une formation s'étendra généralement à tous les questions évoquées ici en profondeur, en utilisant généralement une expérience pratique.",
 "Une simple et populaire supper, en particulier pendant la saison, est la Pa amb Oli : Pan avec l'huile d'olive, le tomato et touts condiments disponibles tels que la chèvre, le tuna, etc.",
 "Comme la population positive à la VIH agisse, les questions telles que la hypertension et la diabète doivent être pris en compte lorsqu'on ait en train d'initier l'ART.",
 "La région du Chaco était l'hôte d'autres groupes de tribes autochtones comme les Guaycur et Payaguá, qui s'établiront par la chasse, la collectivité et la pêche.",
 "L'État partie serait également chargé de la garde des combattants de l'ISIS qui, selon la déclaration, ont été retombés par les pays européens.",
 "L'après-midi, le président américain Donald Trump a annoncé que les troupes américaines seraient à l'exclusion de la Syrie.",
 "Même si Winfrey a été tremblée lors de son farewell, elle a fait clairement à ses fans qu'elle s'arrivera.",
 "Thirty-two grafts de sèvres à sèvres ont été étudiés et les grafts ont été établies dans deux groupes selon la nature de la cote d'excision : groupe I consiste à des patients qui ont undergone l'excision tangentiale et l'étayage à sèvres",
 "Métriques pour quantifier l'utilisation antimicrobiens dans les étoiles de bétail.",
 'Il a eu une puissance omniprésente qui a affecté tous, du roi à la comménère.',
 "Cela permettra aux joueurs de contrôler les actions et les mouvements dans les jeux vidéos en movant le dispositif à travers l'air.",
 "Un cocktail d'antibodies, ZMapp, a eu une promesse dans ce domaine, mais les études officielles indiquent qu'il avait moins de bénéfice que l'on avait souhaité en prévenir la mort.",
 'La pronunciation est relativement facile en Italienne, car la plupart des mots sont pronunciés exactement comme ils sont écrits',
 "Les mutations dans les cellules germineuses peuvent être transmissées à l'enfant, alors que les mutations ailleurs peuvent causer la mort des cellules ou le cancer.",
 "Pour communiquer efficacement les données sur l'utilisation des médicaments antimicrobiens, l'évaluation du lecteur cible est essentielle pour la présentation des renseignements.",
 "Votre fournisseur de services de téléphone local devrait pouvoir donner plus d'information sur la connexion à ce service."]

In [101]:
phrases_df["traduction_google"]=translation

In [102]:
phrases_df

,en,fr,traduction_helsinki,traduction_gpt,traduction_google
0,Decorate your home for the holidays with these...,Décorez votre chez-vous pour les fêtes avec ce...,Décorez votre maison pour les vacances avec ce...,Décorez votre maison pour les fêtes avec ces l...,Décorer votre maison pour les fêtes avec ces é...
1,"In the churchyard, there are interesting marbl...","Dans le cimetière, on trouve d'intéressantes s...","Dans la cour de l'église, il y a d'intéressant...","Dans le cimetière, il y a d'intéressantes scul...","Dans le jardin de la église, il y a des sculpt..."
2,Bipedal specializations are found in Australop...,On trouve des spécialisations bipèdes dans les...,On trouve des spécialisations bipédiques dans ...,Des spécialisations bipèdes sont observées dan...,Les spécifications bipedales sont trouvées dan...
3,Although three people were inside the house wh...,Bien que trois personnes aient été présentes d...,Bien que trois personnes se trouvaient à l'int...,Bien que trois personnes se trouvaient à l'int...,Bien que trois personnes étaient à l'intérieur...
4,A course will normally cover all the issues di...,Un cours couvrira normalement toutes les quest...,Un cours portera normalement sur toutes les qu...,Un cours couvrira normalement toutes les quest...,Une formation s'étendra généralement à tous le...
5,"A simple popular dinner, especially during the...","Un dîner simple et populaire, surtout en été, ...","Un simple dîner populaire, surtout pendant l'é...","Un dîner simple et populaire, surtout pendant ...","Une simple et populaire supper, en particulier..."
6,"As the HIV-positive population ages, issues su...",À mesure que la population VIH-positive vieill...,À mesure que la population séropositive vieill...,À mesure que la population séropositive au VIH...,"Comme la population positive à la VIH agisse, ..."
7,The Chaco region was home to other groups of i...,D'autres tribus indigènes qui peuplaient le Ch...,La région du Chaco abrite d ' autres groupes d...,La région du Chaco était le foyer d'autres gro...,La région du Chaco était l'hôte d'autres group...
8,Turkey would also take over guarding captured ...,La Turquie prendrait également en charge la ga...,La Turquie prendrait également le contrôle des...,La Turquie prendrait également en charge la ga...,L'État partie serait également chargé de la ga...
9,"Late on Sunday, the United States President Do...","Tard dimanche, le président des États-Unis Don...","À la fin de dimanche, le président américain D...","Tard dimanche, le président des États-Unis Don...","L'après-midi, le président américain Donald Tr..."
10,"Although Winfrey was tearful in her farewell, ...","Malgré les larmes versées lors de ses adieux, ...","Bien que Winfrey ait pleuré dans ses adieux, e...",Bien que Winfrey ait été en larmes lors de ses...,Même si Winfrey a été tremblée lors de son far...
11,Thirty-two split-skin grafts were studied and ...,Trente-deux greffes de demi-épaisseur ont été ...,Trente-deux greffes de peau fendue ont été étu...,Trente-deux greffes de peau mince ont été étud...,Thirty-two grafts de sèvres à sèvres ont été é...
12,Metrics for quantifying antimicrobial use in b...,RésuméParamètres pour quantifier l’utilisation...,Mesures pour quantifier l'utilisation d'antimi...,Métriques pour quantifier l'utilisation d'anti...,Métriques pour quantifier l'utilisation antimi...
13,Its all-pervading power affected everyone from...,Son pouvoir omniprésent touchait tout le monde...,Son pouvoir tout-pervade a affecté tout le mon...,Son pouvoir omniprésent a affecté tout le mond...,Il a eu une puissance omniprésente qui a affec...
14,This will allow players to control actions and...,Cela permettra aux joueurs de contrôler les ac...,Cela permettra aux joueurs de contrôler les ac...,Cela permettra aux joueurs de contrôler les ac...,Cela permettra aux joueurs de contrôler les ac...
15,"One antibody cocktail, ZMapp, initially showed...",Même si l'administration d'un cocktail d'antic...,"Un cocktail d'anticorps, ZMapp, s'est montré i...","Un cocktail d'anticorps, ZMapp, a d'abord mont...","Un cocktail d'antibodies, ZMapp, a eu une prom..."
16,Pronunciation is relatively easy in Italian si...,La prononciation est relativement facile en it...,La prononciation est relativement facile en it...,La prononciation est relativement facile en it...,La pronunciation est relativement facile en It...
17,Only mutations in germ-line cells can be passe...,Seules les mutations des cellules germinales p...,Seules les mutations dans les cellules germina...,Seules les mutations dans les cellules germina...,Les mutations dans les cellules germineuses pe...
18,To effectively communicate antimicrobial drug ...,Afin de communiquer efficacement les données c...,Pour communiquer efficacement les données sur ...,Pour communiquer efficacement les données sur ...,Pour communiquer efficacement les données sur ...
19,Your local telephone service provider should b...,Votre opérateur téléphonique local devrait pou...,Votre fournisseur local de services téléphoniq...,Votre fournisseur de services téléphoniques lo...,Votre fournisseur de services de téléphone loc...

In [103]:
phrases_df.to_csv("samples_traductions.csv")

###Evaluation des traductions de google/flan-t5-large

Évaluation avec BLEU

In [104]:
#BLEU
score_bleu3=bleu.corpus_score(translation,[reference])
score_bleu_google=score_bleu3.score
score_bleu_google_norm=score_bleu_google/100
print(f'score bleu google: {score_bleu_google}')
print(f'score bleu google normalisé: {score_bleu_google_norm}')

score bleu google: 20.830137971706836
score bleu google normalisé: 0.20830137971706836

Évaluation avec WER

In [105]:
#WER
wer_google=wer(translation,reference)
wer_google_norm=1-wer_google
print(f'score wer google: {wer_google}')
print(f'score wer google normalisé: {wer_google_norm}')
print(wer_google)

score wer google: 0.7191011235955056
score wer google normalisé: 0.2808988764044944
0.7191011235955056

Évaluation avec BERTScore

In [106]:
result_google=bertscore.compute(predictions=translation,references=reference,lang="fr")["precision"]
result_google

[0.9050360918045044,
 0.8689128756523132,
 0.832839846611023,
 0.8913154006004333,
 0.8503196239471436,
 0.8998602628707886,
 0.801119327545166,
 0.8228422403335571,
 0.8556078672409058,
 0.8836801648139954,
 0.8397172093391418,
 0.8055847883224487,
 0.8740745782852173,
 0.8018815517425537,
 0.9428240656852722,
 0.7859622240066528,
 0.9477502107620239,
 0.92243492603302,
 0.8852402567863464,
 0.8603058457374573]

In [108]:
#score moyen pour le modèle google
mean_precision_google=mean(result_google)

In [109]:
#calcul du score global normalisé des 3 mesures pour google/flan-t5-large
score_moyen_google=score_bleu_google_norm+wer_google_norm+mean_precision_google/3
score_moyen_google

0.7771554120902289

In [110]:
print(f'Score moyen pour le modèle helsinki: {score_moyen_helsinki}')
print(f'Score moyen pour le modèle gpt: {score_moyen_gpt}')
print(f'Score moyen pour le modèle google: {score_moyen_google}')

Score moyen pour le modèle helsinki: 1.2042513878276737
Score moyen pour le modèle gpt: 1.33509010988728
Score moyen pour le modèle google: 0.7771554120902289